ALTER TABLE tokens
ADD COLUMN device_type VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN device_brand VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN device_model VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN os VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN browser VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN country VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN region VARCHAR(255) NOT NULL DEFAULT 'unknown',
ADD COLUMN city VARCHAR(255) NOT NULL DEFAULT 'unknown';